<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-12-24T02:24:54-07:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      api_keys.google.maps
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'America/Creston',
    'api_keys' => [
        'google' => [
            'maps' => 'AIzaSyAypZzBBg5FcDYjQ8GbPBKld1Xs-vfxHwo',
        ],
    ],
];
