<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2024-04-12T11:54:08-07:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.latest_version
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.3.1',
    'version_db_installed' => '20171218000000',
    'maintenance_mode' => false,
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1514020957,
        'latest_version' => '8.3.1',
        'do_page_reindex_check' => false,
    ],
    'calendar' => [
        'topic_attribute' => 'event_categories',
    ],
    'accessibility' => [
        'toolbar_titles' => true,
        'toolbar_tooltips' => true,
        'toolbar_large_font' => false,
        'display_help_system' => true,
    ],
    'mail' => [
        'method' => 'smtp',
        'methods' => [
            'smtp' => [
                'server' => 'mail.coeprobotics.com',
                'username' => 'info@coeprobotics.com',
                'password' => 'info@coepRSC',
                'port' => '',
                'encryption' => '',
                'messages_per_connection' => null,
            ],
        ],
    ],
    'seo' => [
        'redirect_to_canonical_url' => 0,
        'url_rewriting' => false,
    ],
];
