<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-02-19T12:02:18-07:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Robot Study Circle COEP',
            'seo' => [
                'canonical_url' => 'http://coeprobotics.com',
                'canonical_url_alternative' => 'https://coeprobotics.com',
                'canonical_tag' => [
                    'enabled' => false,
                ],
            ],
            'misc' => [
                'favicon_fid' => 35,
                'iphone_home_screen_thumbnail_fid' => 0,
                'modern_tile_thumbnail_fid' => 0,
                'modern_tile_thumbnail_bgcolor' => '',
            ],
        ],
    ],
];
